language: ruby

rvm:
  - 1.8.7
  - 1.9.3

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

script: bundle exec rake

before_script:
  - mysql -e 'create database with_advisory_lock_test'
  - psql -c 'create database with_advisory_lock_test' -U postgres

