language: ruby

rvm:
  - 1.8.7
  - 1.9.3

env:
  - DB=sqlite
  - DB=mysql
  - DB=pg

# 1.8.7 and sqlite fails: "SQL statements in progress: rollback transaction"
matrix:
  exclude:
    - rvm: 1.8.7
      env: DB=sqlite

script: bundle exec rake

before_script:
  - mysql -e 'create database with_advisory_lock_test'
  - psql -c 'create database with_advisory_lock_test' -U postgres

